### ISSUE TITLE
Related stuff worth looking at before implementation :)

### ISSUE THREAD

**Issue by dumblob** [shayanhabibi/loony#1]
a) Nim's [Weave](https://github.com/mratsim/weave/ ) (which offers different queues, work-stealing scheduler with some twists, but most importantly excellent performance - I don't know of any other as generic solution which scales nearly linearly and uses so high percentage of computing power per CPU)

b) https://github.com/ConorWilliams/Forkpool

**Comment by shayanhabibi** [comment]
Thanks for them; I had looked at Weave before but AFAIK it mostly implemented MPSC queues to ensure wait free consumption.

There's nothing wrong with that implementation, but a MPMC is far easier to reason about and implement in any project however not necessarily sharing the performance of multiple MPSC.

Plus I want this to specifically work with CPS 🤣
