### ISSUE TITLE
[NIM] Thread completion triggers thread sanitizer warnings

### ISSUE THREAD

**Issue by shayanhabibi** [shayanhabibi/loony#14]
Thread analyzer determines the [deallocshared](https://github.com/nim-lang/Nim/blob/e3b19cbe52e0578de315d259fbb066bfe991a60f/lib/system/threads.nim#L185) proc called by a thread on completion is a data-race.

Atm only solution I can come up with involves changing or providing a modified std lib thread library that corrects this behaviour. The safest methodology is having the pointer deallocshared acts on being atomically stored and loaded for destruction? Haven't look too deep into it yet.

Related to #9 and #13

**Comment by shayanhabibi** [comment]
I now see the problem is definitely more convoluted and it is not isolated to just the thread deallocation. Numerous other issues are raised despite our own safe understanding of the order of operations with deallocations in loony. For now I think more involved tests that actually have work and require memory coherance to arrive at correct computations is required.

**Comment by disruptek** [comment]
Nim's allocator is buggy and `--define:useMalloc` is the only realistic way forward.
